---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: helloworld-operator-catalogsource
  namespace: default
spec:
  # For the image name, see the following catalog source image names table and use the appropriate value.
  image: 'quay.io/rh_ee_asdas/helloworld-operator-catalog:v0.0.1'
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: helloworld-operator-group
  namespace: default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: helloworld-operator
  namespace: default
spec:
  channel: alpha
  name: helloworld-operator
  source: helloworld-operator-catalogsource
  sourceNamespace: default
  installPlanApproval: Automatic
