apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: helloworld-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HelloWorld is the Schema for the helloworlds API
      displayName: Hello World
      kind: HelloWorld
      name: helloworlds.apps.example.com
      statusDescriptors:
      - description: Conditions represent the latest available observations of an
          object's state
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: helloworld-operator
  displayName: helloworld-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - helloworld-operator
  links:
  - name: Helloworld Operator
    url: https://helloworld-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
